# linear regression
single features and class

In [ ]:
# linear regression
#example from ds class
import numpy as np
from sklearn.linear_model import LinearRegression

# Dataset
X = np.array([[1], [2], [3], [4], [5]])  # Years experience
y = np.array([30000, 35000, 40000, 45000, 50000])  # Salary

# Model
model = LinearRegression()
model.fit(X, y)

# Predict salary for 6 years experience
result = model.predict([[6]])
print("Predicted Salary:", result)

In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
X=np.array([[1],[2],[3],[4],[5]])
y=np.array([2000,4000,6000,8000,10000])
model=LinearRegression()
model.fit(X,y)
result=model.predict([[6]])
print("predicted salary for 6 years",result)

predicted salary for 6 years [12000.]


In [8]:
#salary prediction
import numpy as np 
from sklearn.linear_model import LinearRegression
x=np.array([[1],[2],[3],[4],[5]])
y=np.array([5000,10000,15000,20000,25000]) 
model=LinearRegression()
model.fit(x,y)
result=model.predict([[6]])
print("predicted salary ",result)

predicted salary  [30000.]


In [11]:
import numpy as np 
X = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(-1,1)
print(X)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [12]:
#bill and hosp stay prediction
import numpy as np
from sklearn.linear_model import LinearRegression
X=np.array([1,2,3,4,5,6,7,8]).reshape(-1,1)
y=np.array([5000, 9000, 13000, 17000, 21000, 25000, 29000, 33000])
model=LinearRegression()
model.fit(X,y)
result=model.predict([[9]])
print("9 th day bil for hospital stay",result)

9 th day bil for hospital stay [37000.]


In [18]:
#house size vs sq rate
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([500, 700, 900, 1100, 1300, 1500, 1700, 1900]).reshape(-1, 1)#sqft
y = np.array([20, 28, 35, 42, 50, 58, 65, 72])#price in lakhs
model=LinearRegression()
model.fit(X,y)
result=model.predict([[2500]])
print("2100 sqft is",result)

2100 sqft is [94.69047619]


# Multiple regression
#predicts two different input values
#learns best fit instead of line


In [25]:

#hospital(age,stay,test vs bill)
X = np.array([
    [25, 2, 3],
    [30, 3, 4],
    [35, 4, 5],
    [40, 5, 6],
    [45, 6, 7],
    [50, 7, 8],
    [55, 8, 9],
    [60, 9, 10]
])

# Hospital Bill Amount (₹)
y = np.array([
    12000,
    18000,
    24000,
    30000,
    36000,
    42000,
    48000,
    54000
])
model=LinearRegression()
model.fit(X,y)
result=model.predict([[30,3,5]])
print("predicted bill",result)

predicted bill [18222.22222222]


In [26]:
#student peformance prediction
#student(hours studied,attendence,assignment)
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([
    [2, 60, 3],
    [3, 65, 4],
    [4, 70, 5],
    [5, 75, 6],
    [6, 80, 7],
    [7, 85, 8],
    [8, 90, 9],
    [9, 95, 10]
])

y = np.array([45, 52, 58, 65, 72, 80, 88, 95])#(score)
model=LinearRegression()
model.fit(X,y)
result=model.predict([[5,50,10]])
print("predicted score",result)


predicted score [33.61507937]


In [27]:
#sales prediction
import numpy as np
from sklearn.linear_model import LinearRegression
X = np.array([
    [1000, 500, 5],
    [1500, 700, 5],
    [2000, 900, 10],
    [2500, 1200, 10],
    [3000, 1500, 15],
    [3500, 1800, 15],
    [4000, 2200, 20],
    [4500, 2600, 20]
])#ad ,productvalue,discount

y = np.array([12000, 15000, 19000, 23000, 28000, 33000, 39000, 45000])#productprice
model=LinearRegression()
model.fit(X,y)
result=model.predict([[5000,500,10]])
print("predicted price ",result)

predicted price  [15727.27272727]


# polynomial regression
#used for curved data 

In [30]:
#polynomial regression
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
X = np.array([1, 2, 3, 4, 5, 6]).reshape(-1, 1)#exp
y = np.array([3, 5, 8, 12, 17, 23])#salary in lakhs
poly=PolynomialFeatures(degree=2)
Xpoly=poly.fit_transform(X)
model=LinearRegression()
model.fit(Xpoly,y)
prediction=model.predict(poly.transform([[7]]))
print(prediction)

[30.]


In [35]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
X=np.array([1,2,3,4,5]).reshape(-1,1)
y=np.array([500,600,900,1500,2100])
poly=PolynomialFeatures(degree=2)
Xpoly=poly.fit_transform(X)
model=LinearRegression()
model.fit(Xpoly,y)
prediction=model.predict(poly.transform([[6]]))
print(prediction)

[3000.]


In [8]:
#non const change salary with experience
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
X = [
    [1],
    [2],
    [3],
    [4],
    [5],
    [6],
    [7],
    [8],
    [9],
    [10]
]#experience
y = [
    45000,
    50000,
    60000,
    80000,
    110000,
    150000,
    200000,
    270000,
    350000,
    450000
]#salary
poly=PolynomialFeatures(degree=2)
Xpoly=poly.fit_transform(X)
model=LinearRegression()
model.fit(Xpoly,y)
predict=model.predict(poly.transform([[11]]))
print(predict)

[546333.33333333]


# Ridge Regression
#good choice when all features are necessary
#l2 +linear 
#reduces the weight pf unnecessary features,no features selection , use squared coefficients

In [36]:

import numpy as np
from sklearn.linear_model import Ridge
X = np.array([
    [1000, 2, 15],
    [1200, 2, 12],
    [1500, 3, 10],
    [1800, 3, 8],
    [2000, 4, 6],
    [2200, 4, 5],
    [2500, 5, 3],
    [2800, 5, 2]
])#area,bedroom,distance
y = np.array([30, 38, 50, 62, 75, 85, 100, 115])#house price
model = Ridge(alpha=1.0)
model.fit(X, y)

prediction = model.predict([[1600, 3, 7]])

print("Predicted Price:", prediction)


Predicted Price: [53.14585567]


# lasso Regression 
#to remove unnessary or irrevalent features
#l1+linear regression
#removes the features

In [2]:

import numpy as np
from sklearn.linear_model import Lasso
X = np.array([
    [1, 0, 50, 160],
    [2, 1, 55, 165],
    [3, 1, 60, 170],
    [4, 2, 65, 168],
    [5, 2, 70, 172],
    [6, 3, 75, 169],
    
    [7, 3, 80, 171],
    [8, 4, 85, 170]
])#exp,skill,age,height

y = np.array([
    25000, 30000, 35000, 42000,
    50000, 58000, 68000, 80000
])#salary
model=Lasso(alpha=100)
model.fit(X,y)
predict=model.predict([[4,5,60,189]])
print("predict",predict)
print("coeff",model.coef_)

predict [17865.40361748]
coeff [   0.         -128.82186068 1761.38499594 -816.17932124]


# elastic net
#combines both l1 and l1 regression

In [3]:

import numpy as np
from sklearn.linear_model import ElasticNet
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([30, 35, 40, 80, 100])

model = ElasticNet(alpha=0.1, l1_ratio=0.5)
model.fit(X, y)

print(model.predict([[6]]))
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

[111.07317073]
Coefficients: [18.02439024]
Intercept: 2.9268292682926855


# logistic regression
#predicts only yes or no /0or1
#actually a classification rather than regression

In [7]:

import numpy as np
from sklearn.linear_model import LogisticRegression
X = [[25,22],
     [35,30],
     [40,32],
     [28,24]]

y = [0,1,1,0]
model=LogisticRegression()
model.fit(X,y)
predict=model.predict([[45,20]])
print(predict)
probab=model.predict_proba([[45,20]])
print(probab)

[1]
[[0.02830592 0.97169408]]


In [11]:
#diabetes prediction using logistic regression
import numpy as np
from sklearn.linear_model import LogisticRegression
X = [
    [22, 21.5, 85, 70, 80],
    [28, 24.0, 90, 72, 85],
    [35, 28.5, 140, 80, 120],
    [40, 32.0, 160, 85, 150],
    [50, 30.5, 170, 90, 160],
    [30, 23.0, 95, 75, 90],
    [45, 29.0, 155, 88, 140],
    [25, 22.0, 88, 70, 82]
]#age,bmi,glu,bp,insulin
y = [0, 0, 1, 1, 1, 0, 1, 0]#diabetes
model=LogisticRegression()
model.fit(X,y)
predict=model.predict([[35,23.5,120,80,80]])
proba=model.predict_proba([[35,23.5,120,80,80]])
print(predict)
print(proba)

[0]
[[0.92871971 0.07128029]]


In [12]:
#email spam det
import numpy as np
from sklearn.linear_model import LogisticRegression
X = [
    [120, 2, 0, 0, 500],   
    [80, 0, 0, 0, 300],    
    [200, 5, 1, 1, 800],  
    [150, 4, 1, 1, 700],  
    [60, 0, 0, 0, 250],    
    [300, 10, 1, 1, 1000], 
    [90, 1, 0, 0, 400],    
    [250, 6, 1, 1, 900],   
    [70, 0, 0, 0, 280],   
    [180, 3, 1, 0, 650]    
]#words,links,free wo,winwo,mail length
y=y = [0, 0, 1, 1, 0, 1, 0, 1, 0, 1]#spam or not
model=LogisticRegression()
model.fit(X,y)
predict=model.predict([[150,10,0,1,800]])
proba=model.predict_proba([[[150,10,0,1,800]])
print(predict)
print(proba)

In [6]:
#loan approval pred
import numpy as np
from sklearn.linear_model import LogisticRegression
X = [
    [25, 25000, 650, 500000, 8000, 2],
    [30, 40000, 700, 600000, 9000, 5],
    [45, 80000, 800, 1000000, 12000, 15],
    [22, 15000, 550, 300000, 5000, 1],
    [35, 50000, 720, 700000, 10000, 7],
    [28, 30000, 680, 450000, 7500, 3],
    [50, 90000, 850, 1200000, 15000, 20],
    [23, 20000, 600, 400000, 6000, 1],
    [40, 70000, 780, 900000, 11000, 12],
    [27, 35000, 690, 550000, 8500, 4]
]#[Age, Income, Credit_Score, Loan_Amount, EMI, Employment_Years
y = [0, 1, 1, 0, 1, 1, 1, 0, 1, 1]#approval
model=LogisticRegression()
model.fit(X,y)
predict=model.predict([[30, 50000, 790, 560000, 8500, 6]])
proba=model.predict_proba([[30, 50000, 790, 560000, 8500, 6]])
print(predict)
print(proba)

[1]
[[0. 1.]]


In [3]:
#customer purchase prediction
import numpy as np
from sklearn.linear_model import LogisticRegression
X = [
    [22, 20000, 5, 1, 0],
    [25, 25000, 10, 2, 1],
    [30, 40000, 15, 3, 2],
    [35, 60000, 20, 5, 3],
    [28, 30000, 8, 1, 0],
    [40, 80000, 25, 6, 4],
    [27, 35000, 12, 2, 1],
    [45, 90000, 30, 7, 5],
    [23, 22000, 6, 1, 0],
    [38, 75000, 22, 5, 3]
]#age,salary,web time,ads,previous purchase
y = [0, 0, 1, 1, 0, 1, 0, 1, 0, 1]#will purchase or not
model=LogisticRegression()
model.fit(X,y)
predict=model.predict([[30, 60000, 25,5, 6]])
proba=model.predict_proba([[30, 60000, 25,5, 6]])
print(predict)
print(proba)

[1]
[[4.10896339e-06 9.99995891e-01]]


In [1]:
#churn prediction
import numpy as np
from sklearn.linear_model import LogisticRegression
X = [
    [22, 1, 5, 200, 1],   # age, subscription_months, complaints, monthly_bill, support_calls
    [25, 2, 4, 250, 2],
    [30, 12, 1, 500, 0],
    [35, 24, 0, 800, 0],
    [28, 6, 3, 300, 1],
    [40, 36, 0, 1000, 0],
    [27, 8, 2, 350, 1],
    [45, 48, 0, 1200, 0],
    [23, 3, 5, 220, 2],
    [38, 20, 1, 700, 0]
]#age,subscri month,compl,monthbill
y = [1, 1, 0, 0, 1, 0, 1, 0, 1, 0]#churn or stay
model=LogisticRegression()
model.fit(X,y)
predict=model.predict([[35,20,2,500,2]])
proba=model.predict_proba([[35,20,2,500,2]])
print(predict)
print(proba)

[0]
[[9.99368194e-01 6.31806140e-04]]
